### ISSUE TITLE
About elementHeight

### ISSUE THREAD

**Issue by wayne1203** [seatgeek/react-infinite#137] opened 2016-02-15 04:47 UTC
Hi,
May I know is it available to get <Infinite /> height?
I could like to pass the <Infinite /> height to elementHeight
Because data is getting from internet so doesn't have fixed pattern

Thank you.

**Comment by garetht** [comment] 2016-05-03 14:08
This is a duplicate of https://github.com/seatgeek/react-infinite/issues/61

**Closed by garetht** 2016-05-03 14:08 UTC
