### ISSUE TITLE
Avoid passing elementHeight as an argument

### ISSUE THREAD

**Issue by Volodymyr128** [seatgeek/react-infinite#121] opened 2015-12-18 10:01 UTC
Since all my items are stretchable (their height is calculated dynamically with help of flex-box) I don't want  to calculate their height each time. How can I bypass predefining `elementHeight`?
In other words, how can I pass elements height if I can't know that before mounting?

**Comment by garetht** [comment] 2016-01-21 05:30
This is the chief problem that defies resolution for now.

Closing as a duplicate of #61.

**Closed by garetht** 2016-01-21 05:30 UTC
