### ISSUE TITLE
elementHeight array example

### ISSUE THREAD

**Issue by littlee** [seatgeek/react-infinite#126] opened 2016-01-13 05:58 UTC
Can you provide some example code using an array of elementHeight?

Because I do not know when should I calculate the elementHeight,

my problem is:

I could only know the item's height until they are rendered,
but I should pass an array of elementHeight to render function,
how can I get the elementHeight before rendering ?

**Comment by zenorocha** [comment] 2016-01-18 07:42
+1

**Comment by clauderic** [comment] 2016-01-20 19:54
+1

**Comment by littlee** [comment] 2016-01-21 01:33
I implemented my own infinite scroll eventually

**Comment by garetht** [comment] 2016-01-21 05:29
@littlee I think if you're only looking for the sort of infinite scroll without virtualization (as people call it, apparently) and DOM node reuse there have to be a bunch of libraries ([like this?](https://github.com/guillaumervls/react-infinite-scroll)) out there that will better suit your needs.

As for the dynamic height measurement, closing as a duplicate of https://github.com/seatgeek/react-infinite/issues/61

**Closed by garetht** 2016-01-21 05:29 UTC
