### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Oleksander-Derechei** [seatgeek/react-infinite#251] opened 2017-12-13 11:19 UTC
Hi, I am using react-infinite, and during `npm i` I get:

> react-infinite@0.12.1 requires a peer of react@^15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-infinite@0.12.1 requires a peer of react-dom@^15.5.0 but none is installed. You must install peer dependencies yourself.

Current react version is 16.

Please, update  dependencies.

**Comment by kgregory** [comment] 2017-12-13 15:59
This is a duplicate of #247 and there is a PR pending for this, see #240

cc: @garetht

**Comment by garetht** [comment] 2018-04-04 20:36
This has been released as 0.13.0.

**Closed by garetht** 2018-04-04 20:36 UTC
